---
title: "Activity 9"
author: "Nabhit Arorra"
date: "14th of April 2024"
output: pdf_document
geometry: left=0.5in,right=0.5in,top=0.5in,bottom=0.5in
urlcolor: blue
---

# Question 1
```{r setupFiles, include = FALSE}
# This template file is based off of a template created by Alex Hayes
# https://github.com/alexpghayes/rmarkdown_homework_template

# Setting Document Options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)
```


``` {r}
generate_fibonacci <- function(n) {

  fib <- numeric(n)
  fib[1] <- 1
  fib[2] <- 1
  
  for (i in 3:n) {
    fib[i] <- fib[i-1] + fib[i-2]
  }
  
  return(fib)
}

fib_sequence <- generate_fibonacci(30)
print(fib_sequence)
```

```{r}
myfibo <- function(n) {

  if (n == 1 || n == 2) {
    return(1)
  }
  
  prev = curr = 1
  for (i in 3:n) {
    temp = curr
    curr = prev + curr
    prev = temp
  }
  
  return(curr)
}

print(myfibo(30))
```


# Question 2

```{r}
rootsReal <- function(a, b, c) {
  discriminant <- b^2 - 4*a*c
  return(discriminant >= 0)
}
```

```{r}
print(rootsReal(1, 0, -4))
```

``` {r}
solve_quadratic <- function(a, b, c) {
  discriminant <- b^2 - 4*a*c
  if (discriminant < 0) {
    return("Roots not real")
  } else {
    root1 <- (-b + sqrt(discriminant)) / (2*a)
    root2 <- (-b - sqrt(discriminant)) / (2*a)
    return(c(root1, root2))
  }
}
```

```{r}
print(solve_quadratic(1, 0, -4))

print(solve_quadratic(1, 0, 4))
```